server:
  port: 8761

eureka:
  instance:
    hostname: e-server-git-akshaykemekar-dev.apps.sandbox.x8i5.p1.openshiftapps.com
  client:
    fetch-registry: false 
    register-with-eureka: false 
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
